#!/usr/bin/python
import subprocess
subprocess.call("./textReader")

outputObj = open(r"../RosalindPython5Dir/Output.txt", "r")
myLocation = outputObj.read()
problemFileObj = open(myLocation.strip(), "r")
print problemFileObj.read()

problemFileObj.close()
outputObj.close()
